// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","redirect":"/dashboard","parentId":"1","id":"2"},"3":{"path":"/dashboard","name":"控制台","icon":"DashboardOutlined","parentId":"1","id":"3"},"4":{"path":"/users","name":"用户管理","icon":"UserOutlined","parentId":"1","id":"4"},"5":{"path":"/settings","name":"系统设置","icon":"SettingOutlined","parentId":"1","id":"5"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout" */'@/layouts/BasicLayout.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Users__index" */'@/pages/Users/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Settings__index" */'@/pages/Settings/index.tsx')),
},
  };
}
